"""empty message

Revision ID: 31abcf6daea8
Revises: 6a6e7e375b22
Create Date: 2026-09-23 14:55:41.600574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31abcf6daea8'
down_revision = '6a6e7e375b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=False),
    sa.Column('external_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_account_identity')
    )
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_account_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('external_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
        batch_op.create_index(batch_op.f('ix_favorite_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('external_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
        batch_op.create_index(batch_op.f('ix_image_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('external_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='price::double precision')
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('external_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False))
        batch_op.create_index(batch_op.f('ix_user_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_timestamp'))
        batch_op.drop_column('external_data')
        batch_op.drop_column('updated_timestamp')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('role')

    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               postgresql_using='price::varchar(20)')
        batch_op.drop_column('external_data')
        batch_op.drop_column('updated_timestamp')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_timestamp'))
        batch_op.drop_column('external_data')
        batch_op.drop_column('updated_timestamp')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_timestamp'))
        batch_op.drop_column('external_data')
        batch_op.drop_column('updated_timestamp')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_account_timestamp'))

    op.drop_table('oauth_account')
    # ### end Alembic commands ###
